exclude: ^tests/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-ast
    -   id: debug-statements
    -   id: check-added-large-files
        args: ["--maxkb=100"]
    -   id: check-docstring-first
    -   id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
    -   id: end-of-file-fixer
#    -   id: check-yaml

# flake8
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8

# black
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    args: ["--line-length=79", "--check",]
    language_version: python3
